version: "3.8"

services:
  benchmark-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    profiles:
      - cpu
    volumes:
      - ./results:/app/results
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - ACCELERATOR=cpu
      - BENCHMARK_MODE=${BENCHMARK_MODE:-all}
      - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8080:8080"
    restart: unless-stopped

  benchmark-nvidia:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    profiles:
      - nvidia
    volumes:
      - ./results:/app/results
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - ACCELERATOR=nvidia
      - BENCHMARK_MODE=${BENCHMARK_MODE:-all}
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  benchmark-amd:
    build:
      context: .
      dockerfile: Dockerfile.amd
    profiles:
      - amd
    volumes:
      - ./results:/app/results
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - ACCELERATOR=rocm
      - BENCHMARK_MODE=${BENCHMARK_MODE:-all}
      - HF_TOKEN=${HF_TOKEN}
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    ports:
      - "8080:8080"
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    restart: unless-stopped
